# t = open('text.txt', "r")
# print(t.readlines())
# t.close()
print('\n----read(n)--------------')
# Using read (n)
f = open('Subjects.txt', 'r')
print(f.read(5))
print()
print(f.read(10))

# Using read()
print(' \n-------read()------------')
f = open('Subjects.txt', 'r')
print(f.read())
f.close()

print('\n----readline()------------')
# Using readline ()
f = open('Subjects.txt', 'r')
print(f.readline())
print(f.readline())
print(f.readline(), end=' ')
print(f.readline(), end=' ')
f.close()

print(' \n---readlines()---------------')
# Using readlines ()
f = open('Subjects.txt', 'r')
print(f.readlines())
f.close()
